package ServerApp;


/**
* ServerApp/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, June 11, 2020 6:37:11 o'clock PM EDT
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
