package ServerApp;


/**
* ServerApp/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, June 11, 2020 6:37:11 o'clock PM EDT
*/

public interface ServerOperations 
{
  boolean createPlayerAccount (String firstName, String lastName, String age, String userName, String password, String ipAddress);
  String playerSignIn (String userName, String password, String ipAddress);
  String playerSignOut (String userName, String ipAddress);
  String getPlayerStatus (String userName, String password, String ipAddress);
  boolean transferAccount (String Username, String Password, String OldIPAddress, String NewIPAddress);
  boolean suspendAccount (String userName, String password, String ipAddress, String userNameSuspend);
  void shutDown ();
} // interface ServerOperations
