package ServerApp;


/**
* ServerApp/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, June 11, 2020 6:37:11 o'clock PM EDT
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements ServerApp.ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayerAccount", new java.lang.Integer (0));
    _methods.put ("playerSignIn", new java.lang.Integer (1));
    _methods.put ("playerSignOut", new java.lang.Integer (2));
    _methods.put ("getPlayerStatus", new java.lang.Integer (3));
    _methods.put ("transferAccount", new java.lang.Integer (4));
    _methods.put ("suspendAccount", new java.lang.Integer (5));
    _methods.put ("shutDown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/Server/createPlayerAccount
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String age = in.read_string ();
         String userName = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         boolean $result = false;
         $result = this.createPlayerAccount (firstName, lastName, age, userName, password, ipAddress);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ServerApp/Server/playerSignIn
       {
         String userName = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.playerSignIn (userName, password, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerApp/Server/playerSignOut
       {
         String userName = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.playerSignOut (userName, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ServerApp/Server/getPlayerStatus
       {
         String userName = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.getPlayerStatus (userName, password, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerApp/Server/transferAccount
       {
         String Username = in.read_string ();
         String Password = in.read_string ();
         String OldIPAddress = in.read_string ();
         String NewIPAddress = in.read_string ();
         boolean $result = false;
         $result = this.transferAccount (Username, Password, OldIPAddress, NewIPAddress);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // ServerApp/Server/suspendAccount
       {
         String userName = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         String userNameSuspend = in.read_string ();
         boolean $result = false;
         $result = this.suspendAccount (userName, password, ipAddress, userNameSuspend);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // ServerApp/Server/shutDown
       {
         this.shutDown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
